# -*- coding: utf-8 -*-
"""HC01 - Customer Segmentation GKS-HC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzqENav_htBqv8y-zkWzsnN2Ey_C4ju3
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /gdrive

import pandas as pd
import numpy as np

"""### Import Dataset"""

customer_data = pd.read_csv('/content/drive/MyDrive/Binary Project/Data Analyst HelloCation /Dataset/GKS-Scholarship.csv')
customer_data.head()

"""### Data Cleaning

#### Drop Column
"""

## to-drop column (timestamp, asal_instansi, domisili)
to_drop = ['timestamp',
           'asal_instansi',
           'domisili']
customer_data.drop(to_drop, inplace=True, axis=1)

customer_data.head()

"""#### Drop Missing Value"""

customer_data.wilayah.value_counts().sort_index()

"""### Exploarty Data Analysis"""

# Define a mapping of category labels to numerical values
category_mapping = {
    'jurusan': {'IPA': 1, 'IPS': 2, 'RPL' : 3, 'FISIKA' : 4, 'Administrasi Bisnis' : 5, 'PSIKOLOGI' : 6, 'ILMU EKONOMI' : 7, 'DKV' : 8, 'BAHASA' : 9, 'AKUNTANSI' : 10, 'SCIENCE' : 11, 'PERENCANAAN WILAYAH DAN KOTA' : 12, 'MARKETING' : 13, 'HUBUNGAN INTERNASIONAL' : 14, 'MEDIA KOMUNIKASI' : 15, 'INFORMATIKA' : 16, 'KEHUTANAN' : 17, 'DOKTER GIGI' : 18,  'MANAJEMEN' : 19, 'PERBANKAN SYARIAH' : 20, 'GIZI' : 21, 'DESIGN' : 22, 'KIMIA': 23, 'PENDIDIKAN NON FORMAL' : 24},
    'pilih_kelas' : {'Kelas Private' : 1, 'Kelas Reguler' : 2},
    'apply_study' : {'S1': 1, 'S2' : 2},
    'jenjang' : {'SMA' : 1, 'SMK' : 2, 'MA' : 3, 'Universitas' : 4},
    'wilayah' : {'Banten' : 1, 'Jakarta' : 2, 'Jawa Barat' : 3, 'Jawa Tengah': 4, 'Jawa Timur' : 5, 'Kalimantan Barat' : 6, 'Kepulauan Riau' : 7, 'Nusa Tenggara Barat' : 8, 'Sumatera Barat' : 9, 'Sumatera Selatan' : 10, 'Sumatera Utara' : 11, 'Yogyakarta' : 12},
    'gender' : {'male' : 1, 'female' : 2}
}

# Map the categorical columns to numeric using the defined mapping
customer_data.replace(category_mapping, inplace=True)

# Display the first 6 rows after conversion
print(customer_data.head(6))



"""### Modeling Segmentation"""

